### ISSUE TITLE
this gem name not follow Rubygems name guides

### ISSUE THREAD

**Issue by zw963** [pry/pry-stack_explorer#39]
Hi, i want to write a pry plugins, so, i consider follow pry offical plugins, like this gem.

But, i found this gem not following ruby gems [name-your-gem](https://guides.rubygems.org/name-your-gem/) guide, i want to know, this is on purpose for pry self style, or, just a little
mistaken?

For latter,  i think i can contribute to make it follow guide, and keep one `lib/pry-stack_explorer.rb` for backward compatibility.

Thanks

**Comment by rf-** [comment]
Do you mean that the gem name is wrong or the file structure? I think the name is consistent with the guide, since it’s a plugin for `pry` and its name is `stack_explorer`. 

It’s weird that it’s located in `lib/pry-stack_explorer.rb` instead of `lib/pry/stack_explorer.rb`, but unfortunately it’s currently necessary for compatibility with Pry’s plugin loader. I think the assumption is that users won’t ever need to require it directly since Pry does it at startup time.

**Comment by zw963** [comment]
Cool, i see pry guides, it say like this too, thank!
